PROCESS_DIRECTORY: 'paramsearch'
MODE: 'paramsearch_segmentation' # either 'process', 'paramsearch_segmentation', or 'paramsearch_read-calling'. 'paramsearch' options override 
                # the requested files and tags and performs a small grid search of NUCLEUS_AREA, THRESHOLD_DAPI, and 
                # THRESHOLD_CELL ('paramsearch_segmentation'), or of THRESHOLD_READS ('paramsearch_read-calling'). Segmentation
                # parameters should be chosen either manually or by this parameter search prior to running 'paramsearch_read-calling'.
REQUESTED_FILES: ['combined.csv'] # ignored in paramsearch modes
REQUESTED_TAGS: [ # ignored in paramsearch modes
  'phenotype_aligned.tif',
  'cells.csv',
  'phenotype.csv',
  'annotate_SBS.tif',
  'annotate_SBS_extra.tif',
]
# discarded after processing to save space
TEMP_TAGS: ['aligned.tif', 'maxed.tif', 'std.tif'] # ignored in paramsearch modes

### INPUT TO ANALYSIS
WELL_TILE_LIST: 'input/well_tile_list.csv'
INCLUDE_WELLS_TILES: [['A1',107]] # either 'all' or list of [well,tile] pair lists. If running in either paramsearch modes, sites must be restricted to a subset
INPUT_DIRECTORY: 'input'
BARCODE_TABLE: 'barcodes.csv'
MAGNIFICATION: '10X'
SBS_INPUT_TAG: 'sbs.tif'
SBS_CYCLES: [1, 2, 3, 4, 5, 7, 8, 9, 10] # cycles to include for analysis
SBS_CYCLE_FORMAT: 'c{cycle}-SBS-{cycle}' # python format string

PHENOTYPE_INPUT_TAG: 'phenotype.tif'
PHENOTYPE_CYCLE: 'c0-DAPI-p65ab'

### ANALYSIS PARAMETERS
NUCLEUS_AREA: [[40, 400], [20,800]] # min and max nucleus area in pixels, for paramsearch_segmentation mode can be list of [min,max] lists to test
THRESHOLD_DAPI: [100,200,500]  # threshold for segmenting nuclei, for paramsearch_segmentation mode can be list of thresholds to test
THRESHOLD_CELL: [400,600,800]  # threshold for segmenting cells, for paramsearch_segmentation mode can be list of thresholds to test
THRESHOLD_READS: 75  # threshold for detecting reads, for paramsearch_read-calling mode can be list of thresholds to test
NUCLEUS_PHENOTYPE_FEATURES: [
    'label', # required to join SBS and phenotype data
    'i', 'j', 'area', 
    'dapi_gfp_corr', 
    'dapi_max', 'dapi_mean', 'dapi_median',
    'gfp_max', 'gfp_mean', 'gfp_median',
  ]
CELL_PHENOTYPE_FEATURES: ['label', 'area']

### DISPLAY OPTIONS
DISPLAY_RANGES:
  DAPI: [500, 15000]
  SBS_G: [100, 10000]
  SBS_T: [100, 20000]
  SBS_A: [100, 8000]
  SBS_C: [100, 6000]
LUTS:
  DAPI: 'GRAY'
  SBS_G: 'GREEN'
  SBS_T: 'RED'
  SBS_A: 'MAGENTA'
  SBS_C: 'CYAN'
